import { ScrollView, View } from "react-native";
import React from "react";
import { MotiView, MotiImage } from "moti";
import {Text} from '@/components/ui/Text'

export default function AiTutorialStepFourth() {
    const reportItems = [
        { label: "Total Spent", value: "1,250 zł", color: "#6b5aed" },
        { label: "Saved", value: "+555 zł", color: "#16c47f" },
        { label: "Top Category", value: "Food 45%", color: "#ff6b6b" },
    ];

    return (
        <View className="flex-1 flex flex-col justify-between items-center w-full py-8">
            {/* Report section */}
            <ScrollView showsVerticalScrollIndicator={false} className="flex-1">
                <View className="items-center justify-center w-full gap-6">
                    {/* AI Buddy */}
                    <MotiView
                        from={{ opacity: 0, scale: 0.7, rotate: "-15deg" }}
                        animate={{ opacity: 1, scale: 1, rotate: "0deg" }}
                        transition={{
                            type: "spring",
                            damping: 15,
                            stiffness: 100,
                            delay: 200,
                        }}
                        className="items-center mb-4"
                    >
                        <MotiImage
                            source={require("@/assets/images/aibuddy4.png")}
                            className="w-40 h-40 object-contain"
                            animate={{
                                translateY: [-8, 0, -8],
                                scale: [1, 1.03, 1],
                            }}
                            transition={{
                                loop: true,
                                type: "timing",
                                duration: 2500,
                            }}
                        />
                    </MotiView>

                    {/* Report Card */}
                    <MotiView
                        from={{ opacity: 0, translateY: 40, scale: 0.9 }}
                        animate={{
                            opacity: 1,
                            translateY: 0,
                            scale: 1,
                        }}
                        transition={{
                            type: "spring",
                            damping: 100,
                            delay: 500,
                        }}
                        className="bg-white rounded-3xl p-6 w-full"
                        style={{
                            shadowColor: "#000",
                            shadowOpacity: 0.12,
                            shadowRadius: 15,
                            elevation: 6,
                        }}
                    >
                        <MotiView
                            animate={{
                                translateY: [-4, 0, -4],
                            }}
                            transition={{
                                loop: true,
                                duration: 3000,
                                type: "timing",
                            }}
                        >
                            {/* Header */}
                            <View className="mb-5 pb-4 border-b border-gray-200">
                                <Text className="text-[#6b5aed] font-bold text-xl">
                                    October Report
                                </Text>
                                <Text className="text-gray-500 text-xs mt-1">
                                    Generated by AI
                                </Text>
                            </View>

                            {/* Stats Grid */}
                            <View className="gap-3">
                                {reportItems.map((item, index) => (
                                    <MotiView
                                        key={index}
                                        from={{ opacity: 0, translateX: -20 }}
                                        animate={{ opacity: 1, translateX: 0 }}
                                        transition={{
                                            type: "spring",
                                            damping: 15,
                                            delay: 800 + index * 150,
                                        }}
                                        className="bg-[#f2f0ff] rounded-2xl p-4 flex-row justify-between items-center w-full"
                                    >
                                        <Text className="text-gray-700 font-semibold text-sm">
                                            {item.label}
                                        </Text>
                                        <Text
                                            className="font-bold text-xl"
                                            style={{ color: item.color }}
                                        >
                                            {item.value}
                                        </Text>
                                    </MotiView>
                                ))}
                            </View>
                        </MotiView>
                    </MotiView>
                </View>
            </ScrollView>

            {/* Text Content */}
            <MotiView
                from={{ opacity: 0, translateY: 20 }}
                animate={{ opacity: 1, translateY: 0 }}
                transition={{
                    type: "timing",
                    duration: 600,
                    delay: 1000,
                }}
                className="w-full px-4"
            >
                <Text className="text-left font-bold text-white text-4xl leading-tight">
                    Smart reports{'\n'}every month
                </Text>
                <Text className="text-left font-semibold text-white/80 text-xl mt-4 leading-7">
                    AI analyzes your spending and creates detailed reports with personalized recommendations
                </Text>
            </MotiView>
        </View>
    );
}
